<!doctype html>
<html lang="no">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#152d24">
  <title>Mine sider</title>
  <style>
    :root{color-scheme:light;--bg:#f4f6f3;--panel:#fff;--ink:#14211b;--muted:#647168;--line:#dce4de;--brand:#176b4d;--soft:#e9f5ee;--shadow:0 16px 50px rgba(18,59,44,.09)}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 80% 0,#d9eee1 0,transparent 32%),var(--bg);color:var(--ink);font-family:Inter,"Segoe UI",system-ui,sans-serif}.shell{width:min(1120px,calc(100% - 32px));margin:auto;padding:52px 0 64px}.hero{display:flex;justify-content:space-between;gap:30px;align-items:flex-end;margin-bottom:28px}.eyebrow{margin:0 0 8px;color:var(--brand);font-size:.75rem;font-weight:850;letter-spacing:.12em;text-transform:uppercase}h1{margin:0 0 12px;font-size:clamp(3rem,7vw,5.6rem);line-height:.95;letter-spacing:-.06em}.lead{max-width:620px;margin:0;color:var(--muted);font-size:1.05rem;line-height:1.6}.search{display:grid;gap:7px;width:min(340px,100%);color:var(--muted);font-size:.78rem;font-weight:800}.search input{min-height:50px;border:1px solid #bac9bf;border-radius:14px;padding:0 15px;background:#fff;color:var(--ink);font:inherit;box-shadow:var(--shadow)}.search input:focus{outline:3px solid #176b4d1f;border-color:var(--brand)}.section-heading{display:flex;justify-content:space-between;align-items:end;gap:16px;margin:28px 0 14px}.section-heading h2{margin:0;font-size:1.3rem}.section-heading span{color:var(--muted);font-size:.83rem}.recent{display:none;margin-bottom:18px;padding:16px 18px;border:1px solid #bdd6c6;border-radius:17px;background:var(--soft)}.recent.visible{display:flex;justify-content:space-between;align-items:center;gap:16px}.recent a{color:var(--brand);font-weight:850;text-decoration:none}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.app-card{position:relative;display:grid;gap:16px;min-height:245px;padding:22px;border:1px solid var(--line);border-radius:21px;background:rgba(255,255,255,.94);box-shadow:0 10px 34px rgba(18,59,44,.06);transition:transform .18s,border-color .18s,box-shadow .18s}.app-card:hover{transform:translateY(-3px);border-color:#aec8b8;box-shadow:var(--shadow)}.app-card[hidden]{display:none}.app-top{display:flex;justify-content:space-between;align-items:start;gap:10px}.icon{display:grid;place-items:center;width:46px;height:46px;border-radius:14px;background:var(--tone,#176b4d);color:#fff;font-size:1.2rem;font-weight:900}.tag{padding:5px 8px;border-radius:999px;background:#eef2f0;color:#536159;font-size:.68rem;font-weight:850}.app-card h2{margin:0;font-size:1.35rem}.app-card p{margin:5px 0 0;color:var(--muted);line-height:1.5}.app-card>a{display:flex;justify-content:space-between;align-items:center;align-self:end;padding-top:14px;border-top:1px solid var(--line);color:var(--brand);font-weight:850;text-decoration:none}.empty{padding:28px;border:1px dashed #b8c6bd;border-radius:18px;text-align:center;color:var(--muted)}.footer{margin-top:30px;color:var(--muted);font-size:.78rem}
    @media(max-width:850px){.hero{align-items:flex-start;flex-direction:column}.search{width:100%}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.shell{width:min(100% - 20px,1120px);padding-top:30px}.grid{grid-template-columns:1fr}.app-card{min-height:215px}.recent.visible{align-items:flex-start;flex-direction:column}}
  </style>
</head>
<body>
  <main class="shell">
    <header class="hero"><div><p class="eyebrow">Personlig portal</p><h1>Mine sider.</h1><p class="lead">Alle verktøyene samlet i én rolig og søkbar startside.</p></div><label class="search"><span>Finn en app</span><input id="appSearch" type="search" placeholder="Søk på navn eller oppgave" autocomplete="off"></label></header>
    <aside class="recent" id="recentApp"><div><p class="eyebrow">Sist brukt</p><strong id="recentName">–</strong></div><a id="recentLink" href="#">Fortsett →</a></aside>
    <div class="section-heading"><h2>Apper og tjenester</h2><span id="appCount" aria-live="polite">6 apper</span></div>
    <section class="grid" id="appGrid">
      <article class="app-card" data-name="borettslag parkering avfall tjenester"><div class="app-top"><span class="icon">B</span><span class="tag">Borettslag</span></div><div><h2>Borettslaget</h2><p>Parkering, køplass, kontrakter og avfallsstasjoner.</p></div><a href="borettslag/index.html" data-app="Borettslaget">Åpne <span>→</span></a></article>
      <article class="app-card" data-name="krypto investering portefølje bitcoin ordre"><div class="app-top"><span class="icon" style="--tone:#6b4fb3">K</span><span class="tag">Økonomi</span></div><div><h2>Kryptooversikt</h2><p>Portefølje, livepriser, kjøp, salg og investeringsjournal.</p></div><a href="crypto-tracker/index.php" data-app="Kryptooversikt">Åpne <span>→</span></a></article>
      <article class="app-card" data-name="trening kroppsmål bilde utvikling logg"><div class="app-top"><span class="icon" style="--tone:#176e79">T</span><span class="tag">Helse</span></div><div><h2>Treningslogg</h2><p>Kroppsmål, trender, fremgangsbilder og historikk.</p></div><a href="treningslogg/index.php" data-app="Treningslogg">Åpne <span>→</span></a></article>
      <article class="app-card" data-name="bolig avkastning lån kalkulator fellesgjeld"><div class="app-top"><span class="icon" style="--tone:#986323">H</span><span class="tag">Analyse</span></div><div><h2>Boligkalkulator</h2><p>Avkastning, lånerom, fellesgjeld og lagrede scenarier.</p></div><a href="boligavkastning/index.html" data-app="Boligkalkulator">Åpne <span>→</span></a></article>
      <article class="app-card" data-name="eiendeler formue verdier gjeld økonomi"><div class="app-top"><span class="icon" style="--tone:#2759a5">V</span><span class="tag">Økonomi</span></div><div><h2>Mine verdier</h2><p>Eiendeler, gjeld, formuesfordeling og verdihistorikk.</p></div><a href="eiendeler/index.php" data-app="Mine verdier">Åpne <span>→</span></a></article>
      <article class="app-card" data-name="pris sammenligning butikk tilbud pdf"><div class="app-top"><span class="icon" style="--tone:#68736d">P</span><span class="tag">Verktøy</span></div><div><h2>Prissammenligning</h2><p>Sammenlign varepriser fra tilbudsdokumenter.</p></div><a href="prissammenligning/index.php" data-app="Prissammenligning">Åpne <span>→</span></a></article>
    </section>
    <p class="empty" id="appEmpty" hidden>Ingen apper matcher søket.</p>
    <footer class="footer">Tips: Startsidens «Sist brukt» lagres bare i denne nettleseren.</footer>
  </main>
  <script>
    (()=>{const input=document.getElementById('appSearch'),cards=Array.from(document.querySelectorAll('.app-card')),count=document.getElementById('appCount'),empty=document.getElementById('appEmpty'),recent=document.getElementById('recentApp');const saved=JSON.parse(localStorage.getItem('portal-recent-app')||'null');if(saved?.name&&saved?.href){document.getElementById('recentName').textContent=saved.name;document.getElementById('recentLink').href=saved.href;recent.classList.add('visible')}input.addEventListener('input',()=>{const term=input.value.trim().toLocaleLowerCase('nb-NO');let visible=0;cards.forEach(card=>{const show=!term||card.dataset.name.includes(term);card.hidden=!show;if(show)visible++});count.textContent=`${visible} ${visible===1?'app':'apper'}`;empty.hidden=visible!==0});document.querySelectorAll('[data-app]').forEach(link=>link.addEventListener('click',()=>localStorage.setItem('portal-recent-app',JSON.stringify({name:link.dataset.app,href:link.getAttribute('href')}))))})();
  </script>
</body>
</html>
